### ISSUE TITLE
Good file structure but...

### ISSUE THREAD

**Issue by martinbagshaw** [FAC-Sixteen/week-3-project-daabest#17]
Good file structure, though some things could be improved to make it less ambiguous:
- styles folder contains images, not just css. This could get confusing
- 'scripts' is fine if just a frontend project, but in future weeks, you may find it useful to separate frontend and backend scripts into folders such as 'public' and 'src' for frontend and backend concerns respectively.

![Screen Shot 2019-03-22 at 10 15 48](https://user-images.githubusercontent.com/28146666/54816191-8cecb900-4c8b-11e9-92bc-ad9e4c12253c.png)

**Comment by tloth** [comment]
Done! Thanks!
