### ISSUE TITLE
Accessibility bits and html

### ISSUE THREAD

**Issue by martinbagshaw** [FAC-Sixteen/week-3-project-daabest#30]
- description and viewport meta tags [can be added](https://www.w3schools.com/tags/tag_meta.asp)
- add a label to the text input, with [for attribute and id matching](https://www.w3schools.com/tags/att_label_for.asp)
- sections should start with or contain h1 - h6 headings to say what they are about, preferrably in descending order
- if you can throw in an image alt attribute from the api, that would be great.

**Comment by tloth** [comment]
also lang=en!

**Comment by martinbagshaw** [comment]
> also lang=en!
👍

**Comment by aniablaziak** [comment]
fixed it! 🙃
